### ISSUE TITLE
make xf86-input-libinput a dependency of xorg-server

### ISSUE THREAD

**Issue by apprehensions** [echawk/kiss-xorg#146]
there is no reason not to.

**Comment by ehawkvu** [comment]
it would cause a circular dependency

**Comment by apprehensions** [comment]
make it a soft dependency by checking with kiss l

**Comment by apprehensions** [comment]
this is how it should be done though:
xorg-server -> xf86-input-libinput -> libinput

**Comment by ehawkvu** [comment]
The issue with making it a soft dependency like that is that anytime someone tries bootstrapping an xorg-system, they are going to have to ensure that they *explicity* add xf86-input-libinput to the packages that they need.

I personally don't see this as a problem, as this has been how kiss has been since 2019. Would adding a comment to `xorg-server`'s post-installation script resolve this issue?

**Comment by apprehensions** [comment]
post-install is cool, but if the user launched Xorg their system is basically useless and have to force reset.

libinput is a dependency of xorg-server and its post-install will be drowned with the rest of packages listed as dependencies of xorg-server.

just make xf86-input-libinput a dependency of xorg-server, in which xf86-input-libinput is also requires libinput.

**Comment by echawk** [comment]
Resolved as of: c55ce50
